/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author EDY TCHOKOUANI
 */
public class JF_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JF_Principal
     */
    public JF_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Gestion_Production = new javax.swing.JMenu();
        jMenu_Gestion_Souscripteurs = new javax.swing.JMenu();
        jMenu_Gestion_Surccusales = new javax.swing.JMenu();
        jMenu_Gestion_Assures = new javax.swing.JMenu();
        jMenu_Gestion_Compagnies = new javax.swing.JMenu();
        jMenu_Gestion_Tarifs = new javax.swing.JMenu();
        jMenu_Gestion_Polices = new javax.swing.JMenu();
        jMenu_Gestion_Prestataires = new javax.swing.JMenu();
        jMenu_Conseil_Medicaux = new javax.swing.JMenu();
        jMenu_Gestion_Exercice = new javax.swing.JMenu();
        jMenu_Gestion_Sinistre = new javax.swing.JMenu();
        jMenu_Gestion_BPC = new javax.swing.JMenu();
        jMenu_Gestion_Decompte = new javax.swing.JMenu();
        jMenu_Gestion_Remboursements = new javax.swing.JMenu();
        jMenu_Etats_Statistiques = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_Gestion_Production.setText("Gestion Production");

        jMenu_Gestion_Souscripteurs.setText("Gestion Souscripteurs");
        jMenu_Gestion_Production.add(jMenu_Gestion_Souscripteurs);

        jMenu_Gestion_Surccusales.setText("Gestion Surccusales");
        jMenu_Gestion_Production.add(jMenu_Gestion_Surccusales);

        jMenu_Gestion_Assures.setText("Gestion Assurés");
        jMenu_Gestion_Production.add(jMenu_Gestion_Assures);

        jMenu_Gestion_Compagnies.setText("Gestion Compagnies");
        jMenu_Gestion_Production.add(jMenu_Gestion_Compagnies);

        jMenu_Gestion_Tarifs.setText("Gestion Tarifs");
        jMenu_Gestion_Production.add(jMenu_Gestion_Tarifs);

        jMenu_Gestion_Polices.setText("Gestion Polices");
        jMenu_Gestion_Production.add(jMenu_Gestion_Polices);

        jMenu_Gestion_Prestataires.setText("Gestion Prestataires");
        jMenu_Gestion_Production.add(jMenu_Gestion_Prestataires);

        jMenu_Conseil_Medicaux.setText("Gestion Conseils Medicaux");
        jMenu_Gestion_Production.add(jMenu_Conseil_Medicaux);

        jMenu_Gestion_Exercice.setText("Cloture/Ouverture");
        jMenu_Gestion_Production.add(jMenu_Gestion_Exercice);

        jMenuBar1.add(jMenu_Gestion_Production);

        jMenu_Gestion_Sinistre.setText("Gestion Sinistre");

        jMenu_Gestion_BPC.setText("Gestion Bon Prise en Charge");
        jMenu_Gestion_Sinistre.add(jMenu_Gestion_BPC);

        jMenu_Gestion_Decompte.setText("Gestion Decomptes");
        jMenu_Gestion_Sinistre.add(jMenu_Gestion_Decompte);

        jMenu_Gestion_Remboursements.setText("Gestion Remboursements");
        jMenu_Gestion_Sinistre.add(jMenu_Gestion_Remboursements);

        jMenu_Etats_Statistiques.setText("Etats Statistiques");
        jMenu_Gestion_Sinistre.add(jMenu_Etats_Statistiques);

        jMenuBar1.add(jMenu_Gestion_Sinistre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Conseil_Medicaux;
    private javax.swing.JMenu jMenu_Etats_Statistiques;
    private javax.swing.JMenu jMenu_Gestion_Assures;
    private javax.swing.JMenu jMenu_Gestion_BPC;
    private javax.swing.JMenu jMenu_Gestion_Compagnies;
    private javax.swing.JMenu jMenu_Gestion_Decompte;
    private javax.swing.JMenu jMenu_Gestion_Exercice;
    private javax.swing.JMenu jMenu_Gestion_Polices;
    private javax.swing.JMenu jMenu_Gestion_Prestataires;
    private javax.swing.JMenu jMenu_Gestion_Production;
    private javax.swing.JMenu jMenu_Gestion_Remboursements;
    private javax.swing.JMenu jMenu_Gestion_Sinistre;
    private javax.swing.JMenu jMenu_Gestion_Souscripteurs;
    private javax.swing.JMenu jMenu_Gestion_Surccusales;
    private javax.swing.JMenu jMenu_Gestion_Tarifs;
    // End of variables declaration//GEN-END:variables
}
